### ISSUE TITLE
Cannot find module '<project-base>/node_modules/stylelint/dist/cli.js'

### ISSUE THREAD

**Issue by sanchezelton** [rahulsom/linters#1]
I tried executing the stylelint task and received the error as indicated in the subject. Here is an output of gradle stylelint --info:

```
Connected to daemon DaemonInfo{pid=20331, address=[173c3853-38d4-4a8e-ab8d-557deedc08f4 port:42700, addresses:[/0:0:0:0:0:0:0:1%lo, /127.0.0.1]], idle=true, lastBusy=1485540458413, context=DefaultDaemonContext[uid=562d1ce9-31f5-40a6-bdee-80270ede3659,javaHome=/usr/lib/jvm/java-8-oracle,daemonRegistryDir=/home/net/.gradle/daemon,pid=20331,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]}. Dispatching request Build{id=23338e90-0509-40e9-aaa9-e708d65a4461.1, currentDir=/home/net/dev/my-project/my-subproject}.
Received result org.gradle.launcher.daemon.protocol.BuildStarted@24c4ddae from daemon DaemonInfo{pid=20331, address=[173c3853-38d4-4a8e-ab8d-557deedc08f4 port:42700, addresses:[/0:0:0:0:0:0:0:1%lo, /127.0.0.1]], idle=true, lastBusy=1485540458413, context=DefaultDaemonContext[uid=562d1ce9-31f5-40a6-bdee-80270ede3659,javaHome=/usr/lib/jvm/java-8-oracle,daemonRegistryDir=/home/net/.gradle/daemon,pid=20331,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be starting).
The client will now receive all logging from the daemon (pid: 20331). The daemon log file: /home/net/.gradle/daemon/2.14/daemon-20331.out.log
Starting 8th build in daemon [uptime: 15 mins 10.757 secs, performance: 98%, no major garbage collections]
Executing build with daemon context: DefaultDaemonContext[uid=562d1ce9-31f5-40a6-bdee-80270ede3659,javaHome=/usr/lib/jvm/java-8-oracle,daemonRegistryDir=/home/net/.gradle/daemon,pid=20331,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]
Starting Build
Settings evaluated using settings file '/home/net/dev/my-project/settings.gradle'.
Projects loaded. Root project using build file '/home/net/dev/my-project/build.gradle'.
Included projects: [root project 'my-project', project ':common', project ':my-models', project ':my-subproject']
Evaluating root project 'my-project' using build file '/home/net/dev/my-project/build.gradle'.
Evaluating project ':common' using build file '/home/net/dev/my-project/common/build.gradle'.
Evaluating project ':my-models' using build file '/home/net/dev/my-project/my-models/build.gradle'.
Evaluating project ':my-subproject' using build file '/home/net/dev/my-project/my-subproject/build.gradle'.
Applying dependency management to configuration 'archives' in project 'my-subproject'
Applying dependency management to configuration 'compile' in project 'my-subproject'
Applying dependency management to configuration 'compileClasspath' in project 'my-subproject'
Applying dependency management to configuration 'compileOnly' in project 'my-subproject'
Applying dependency management to configuration 'default' in project 'my-subproject'
Applying dependency management to configuration 'runtime' in project 'my-subproject'
Applying dependency management to configuration 'shadow' in project 'my-subproject'
Applying dependency management to configuration 'testCompile' in project 'my-subproject'
Applying dependency management to configuration 'testCompileClasspath' in project 'my-subproject'
Applying dependency management to configuration 'testCompileOnly' in project 'my-subproject'
Applying dependency management to configuration 'testRuntime' in project 'my-subproject'
Applying dependency management to configuration 'findbugsPlugins' in project 'my-subproject'
Applying dependency management to configuration 'findbugs' in project 'my-subproject'
Applying dependency management to configuration 'provided' in project 'my-subproject'
abc release version : 2.0
ABC tests coming soon ...
Configuring agent
All projects evaluated.
Selected primary task 'stylelint' from project :my-subproject
Tasks to be executed: [task ':my-subproject:lintersInit', task ':my-subproject:nodeSetup', task ':my-subproject:installLinters', task ':my-subproject:stylelint']
In-memory cache of /home/net/dev/my-project/.gradle/2.14/taskArtifacts/fileHashes.bin: Size{15230}, CacheStats{hitCount=7924, missCount=15230, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
In-memory cache of /home/net/dev/my-project/.gradle/2.14/taskArtifacts/treeSnapshots.bin: Size{3}, CacheStats{hitCount=0, missCount=2, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
In-memory cache of /home/net/dev/my-project/.gradle/2.14/taskArtifacts/treeSnapshotUsage.bin: Size{1}, CacheStats{hitCount=0, missCount=1, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
In-memory cache of /home/net/dev/my-project/.gradle/2.14/taskArtifacts/fileSnapshotsToTreeSnapshotsIndex.bin: Size{3}, CacheStats{hitCount=0, missCount=3, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
In-memory cache of /home/net/dev/my-project/.gradle/2.14/taskArtifacts/fileSnapshots.bin: Size{7}, CacheStats{hitCount=0, missCount=4, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
In-memory cache of /home/net/dev/my-project/.gradle/2.14/taskArtifacts/taskArtifacts.bin: Size{2}, CacheStats{hitCount=8, missCount=2, loadSuccessCount=0, loadExceptionCount=0, totalLoadTime=0, evictionCount=0}
:my-subproject:lintersInit (Thread[Daemon worker Thread 2,5,main]) started.
:my-subproject:lintersInit
Skipping task ':my-subproject:lintersInit' as it has no actions.
:my-subproject:lintersInit UP-TO-DATE
:my-subproject:lintersInit (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.005 secs.
:my-subproject:nodeSetup (Thread[Daemon worker Thread 2,5,main]) started.
:my-subproject:nodeSetup
Skipping task ':my-subproject:nodeSetup' as it is up-to-date (took 0.058 secs).
:my-subproject:nodeSetup UP-TO-DATE
:my-subproject:nodeSetup (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.061 secs.
:my-subproject:installLinters (Thread[Daemon worker Thread 2,5,main]) started.
:my-subproject:installLinters
Skipping task ':my-subproject:installLinters' as it is up-to-date (took 0.231 secs).
:my-subproject:installLinters UP-TO-DATE
:my-subproject:installLinters (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.238 secs.
:my-subproject:stylelint (Thread[Daemon worker Thread 2,5,main]) started.
:my-subproject:stylelint
Executing task ':my-subproject:stylelint' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Starting process 'command '/home/net/dev/my-project/my-subproject/.gradle/nodejs/node-v0.12.7-linux-x64/bin/node''. Working directory: /home/net/dev/my-project/my-subproject Command: /home/net/dev/my-project/my-subproject/.gradle/nodejs/node-v0.12.7-linux-x64/bin/node /home/net/dev/my-project/my-subproject/node_modules/stylelint/dist/cli.js -f json
Successfully started process 'command '/home/net/dev/my-project/my-subproject/.gradle/nodejs/node-v0.12.7-linux-x64/bin/node''
module.js:338
    throw err;
          ^
Error: Cannot find module '/home/net/dev/my-project/my-subproject/node_modules/stylelint/dist/cli.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
:my-subproject:stylelint FAILED
:my-subproject:stylelint (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.19 secs.
```

I'm using Node 0.12.7. Here's the linters block from my gradle.build file:

```
linters {

    jscs = true

    htmlcs = true

    jshint = true

    stylelint = true

    jsIncludes  = [
        "${frontendJsSrcDir}/**/*.js", 
        "${serverJsSrcDir}/**/*.js"
    ]
    jsExcludes  = [
        "**/bower_components/**", 
        "**/node_modules/**",
        "${frontendJsSrcDir}/resources/dist/js/**",  // filters out bootstrap
        "${frontendJsSrcDir}/components/plumbjs/**",    // filters out plumbjs
        "${frontendJsSrcDir}/customizations/i18n/**"    // filters out angular-i18n
    ]

    htmlIncludes = ["${frontendJsSrcDir}/**/*.html"]
    htmlExcludes = ["**/bower_components/**"]
    stylesIncludes = ["${frontendJsSrcDir}/**/*.less", "${frontendJsSrcDir}/**/*.css"]
    stylesExcludes = ["**/bower_components/**"]

    format = 'checkstyle'
}
```

Also, how do I:

a. indicate an output file for the linting?
and
b. indicate that I want separate files for html, jsHint, and style linting output?

**Comment by rahulsom** [comment]
I hadn't pinned the version of these tools and it looks like `stylelint` has changed how their script is called.
Since I had this cached on my machine, I was able to run it. I'll release a `0.2` with pinned versions soon. Thanks for the bug report.

As far as your answers go, 

>  indicate an output file for the linting?

That is not possible at the moment. However these are produced in the `build` directory.

> indicate that I want separate files for html, jsHint, and style linting output?

That is the only supported behavior.

```
$ ./gradlew htmlcs jscs jshint stylelint 
Download https://nodejs.org/dist/v0.12.7/node-v0.12.7-darwin-x64.tar.gz
:lintersInit UP-TO-DATE
:nodeSetup
:installLinters UP-TO-DATE
:htmlcs
:jscs
:jshint
:stylelint

BUILD SUCCESSFUL

Total time: 43.106 secs

$ ll build/           
total 40
-rw-r--r--  1 rahul  staff   1.5K Jan 28 16:46 checkstyle.htmlcs.xml
-rw-r--r--  1 rahul  staff   4.5K Jan 28 16:46 checkstyle.jscs.xml
-rw-r--r--  1 rahul  staff   4.0K Jan 28 16:46 checkstyle.jshint.xml
-rw-r--r--  1 rahul  staff   108B Jan 28 16:43 checkstyle.stylelint.xml
```

**Comment by rahulsom** [comment]
I pinned the versions, and it works on Node 4+.
It still fails on 0.12.7 because stylelint uses `const`.

```
const getModulePath = require("./utils/getModulePath")
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/rahul/src/hottowel-ratpack/node_modules/stylelint/bin/stylelint.js:5:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
:stylelint FAILED
```

**Comment by rahulsom** [comment]
I've added support for stylelint 6.9.0 in version 0.1.1. That should work for you.
