### ISSUE TITLE
htmlcs failure: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by sanchezelton** [rahulsom/linters#2]
Back again. Still using Node 0.12.7. htmlcs fails during build with the following error:

The same issue can be reproduced on both 0.1.1 and 0.2.
```
abc release version : 2.0
:my-project:lintersInit UP-TO-DATE
:my-project:nodeSetup UP-TO-DATE
:my-project:installLinters UP-TO-DATE
:my-project:htmlcs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':my-project:htmlcs'.
> toIndex = 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Here is the stack generated when using `--stacktrace`

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':my-project:htmlcs'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:237)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.IndexOutOfBoundsException: toIndex = 2
        at com.github.rahulsom.HtmlcsUtil$_writeHtmlcsReport_closure2$_closure9$_closure10.doCall(HtmlcsUtil.groovy:69)
        at com.github.rahulsom.HtmlcsUtil$_writeHtmlcsReport_closure2$_closure9$_closure10.doCall(HtmlcsUtil.groovy)
        at com.github.rahulsom.HtmlcsUtil$_writeHtmlcsReport_closure2$_closure9.doCall(HtmlcsUtil.groovy:68)
        at com.github.rahulsom.HtmlcsUtil$_writeHtmlcsReport_closure2.doCall(HtmlcsUtil.groovy:66)
        at com.github.rahulsom.HtmlcsUtil$_writeHtmlcsReport_closure2.doCall(HtmlcsUtil.groovy)
        at com.github.rahulsom.HtmlcsUtil.writeHtmlcsReport(HtmlcsUtil.groovy:65)
        at com.github.rahulsom.HtmlcsUtil.access$0(HtmlcsUtil.groovy)
        at com.github.rahulsom.HtmlcsUtil$_createHtmlcsTask_closure1$_closure7.doCall(HtmlcsUtil.groovy:52)
        at com.github.rahulsom.HtmlcsUtil$_createHtmlcsTask_closure1$_closure7.call(HtmlcsUtil.groovy)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more
```

Here's the `linters` block from my gradle.build file (for the benefit of not following on this issue):

```
linters {
    jscs = true
    htmlcs = true
    jshint = true
    stylelint = true

    jsIncludes  = [
        "${frontendJsSrcDir}/*/.js", 
        "${serverJsSrcDir}/*/.js"
    ]
    jsExcludes  = [
        "components/ui/frontend/bower_components/**", 
        "**/node_modules/**",
        "${frontendJsSrcDir}/resources/dist/js/**",  // filters out bootstrap
        "${frontendJsSrcDir}/components/plumbjs/**",    // filters out plumbjs
        "${frontendJsSrcDir}/customizations/i18n/**"    // filters out angular-i18n
    ]

    htmlIncludes = ["${frontendJsSrcDir}/*/.html"]
    htmlExcludes = ["**/bower_components/**"]
    stylesIncludes = ["${frontendJsSrcDir}/*/.less", "${frontendJsSrcDir}/*/.css"]
    stylesExcludes = ["**/bower_components/**"]

    format = 'checkstyle' // or 'text'
}
```

**Comment by rahulsom** [comment]
Can you provide the output of `tree` on your `frontendJsSrcDir` directory?

I suspect it has to do with your glob patterns.

E.g.

`"${frontendJsSrcDir}/*/.html"` should possibly be `"${frontendJsSrcDir}/*.html"` or `"${frontendJsSrcDir}/**/*.html"`

**Comment by rahulsom** [comment]
I see the problem in the README in terms of escaping of asciidoctor macros. I've fixed that in cda3a93

**Comment by sanchezelton** [comment]
OK, changed my linters block to use the Ant-like syntax I had seen earlier (I had seen a different glob syntax when working with gulp, but I prefer Ant's "glob" syntax anyhow):

```
linters {
    jscs = true
    htmlcs = true
    jshint = true
    stylelint = true

    jsIncludes  = [
        "${frontendJsSrcDir}/**/*.js", 
        "${serverJsSrcDir}/**/*.js"
    ]
    jsExcludes  = [
        "${frontendJsSrcDir}/resources/dist/js/**",  // filters out bootstrap
        "${frontendJsSrcDir}/components/plumbjs/**",    // filters out plumbjs
        "${frontendJsSrcDir}/customizations/i18n/**"    // filters out angular-i18n
    ]

    htmlIncludes = ["${frontendJsSrcDir}/**/*.html"]
    stylesIncludes = ["${frontendJsSrcDir}/**/*.less", "${frontendJsSrcDir}/**/*.css"]
   // removed htmlExcludes and stylesIncludes because there is no bower_components subdir in ${frontendJsSrcDir}

    format = 'checkstyle' // or 'text'
}
```
Here is tree's output, with some obfuscation and snipping for brevity:
```
.
├── 404.html
├── components
│   ├── access
│   │   ├── access.js
│   │   └── README.txt
│   ├── dragdrop
│   │   └── ngDraggable.js
│   ├── image-preview
│   │   └── angular-media-preview.js
│   ├── input-validator
│   │   ├── input-validator.html
│   │   ├── input-validator.js
│   │   └── _input-validator.scss
│   ├── lazy-form-model
│   │   └── lazyFormModel.js
│   ├── plumbjs
│   │   ├── demo-support.js
│   │   ├── jsPlumb-2.2.6.js
│   │   ├── jsPlumbToolkit-1.1.4.js
│   │   └── jsPlumbToolkit-angular-1.1.4.js
│   ├── abc-collection
│   │   ├── bower.json
│   │   ├── examples
│   │   │   ├── bower.json
│   │   │   └── index.html
│   │   ├── README.md
│   │   └── src
│   │       └── collection.js
│   └── socket.io
│       ├── bower.json
│       ├── README.md
│       └── src
│           └── socket-io.js
├── customizations
│   ├── i18n
│   │   ├── angular-i18n
│   │   │   ├── angular-locale_de-DE.js
│   │   │   ├── angular-locale_en-GB.js
│   │   │   ├── angular-locale_en-US.js
│   │   │   ├── angular-locale_fr-FR.js
│   │   │   ├── angular-locale_hr-HR.js
│   │   │   ├── angular-locale_hu-HU.js
│   │   │   ├── angular-locale_it-IT.js
│   │   │   ├── angular-locale_sk-SK.js
│   │   │   └── readme.md
│   │   ├── locale-de_DE.json
│   │   ├── locale-en_GB.json
│   │   ├── locale-en_US.json
│   │   ├── locale-fr_FR.json
│   │   ├── locale-hr_HR.json
│   │   ├── locale-hu_HU.json
│   │   ├── locale-it_IT.json
│   │   └── locale-sk_SK.json
│   ├── images
│   │   ├── add.png
│   │   ├── alerts
│   │   │   ├── Critical.png
│   │   │   ├── info.png
│   │   │   ├── Major.png
│   │   │   ├── Minor.png
│   │   │   └── warning.png
│   │   ├── bbgr.jpg
│   │   ├── logo-tc.png
│   │   ├── N-overview
│   │   │   ├── graphic_alarms.svg
│   │   │   ├── graphic_license_usage.svg
│   │   │   └── graphic_resources.svg
│   │   ├── paste.png
│   │   ├── pin.jpg
│   │   ├── refresh.png
│   │   ├── save.png
│   │   ├── template
│   │   │   ├── default_profile.svg
│   │   │   ├── email.svg
│   │   │   ├── email-white.svg
│   │   │   └── webfilter.svg
│   │   ├── template-icons
│   │   │   ├── A.svg
│   │   │   ├── B.svg
│   │   │   ├── C.svg
│   │   │   ├── D.svg
│   │   │   ├── engineering.svg
│   │   │   ├── E.svg
│   │   │   ├── F.svg
│   │   │   ├── G.svg
│   │   │   ├── hq.svg
│   │   │   ├── H.svg
│   │   │   ├── I.svg
│   │   │   ├── J.svg
│   │   │   ├── K.svg
│   │   │   ├── L.svg
│   │   │   ├── M.svg
│   │   │   ├── no_profile.svg
│   │   │   ├── N.svg
│   │   │   ├── office.svg
│   │   │   ├── O.svg
│   │   │   ├── P.svg
│   │   │   ├── Q.svg
│   │   │   ├── retail_large.svg
│   │   │   ├── retail.svg
│   │   │   ├── R.svg
│   │   │   ├── S.svg
│   │   │   ├── T.svg
│   │   │   ├── U.svg
│   │   │   ├── V.svg
│   │   │   ├── W.svg
│   │   │   ├── X.svg
│   │   │   ├── Y.svg
│   │   │   └── Z.svg
│   │   ├── toggle.png
│   │   └── wb_t_03.svg
│   └── settings.js
├── filters.js
├── index.html
├── index.js
├── index.scss
├── models
│   ├── actionRequiredModel.js
│   ├── editTemplatesModel.js
│   ├── filterModel.js
│   ├── LanguageModel.js
│   ├── mapModel.js
│   └── siteModel.js
├── services
│   ├── deviceService.js
│   ├── ems.js
│   ├── flagService.js
│   ├── guiHelperService.js
│   ├── highstockchartsService.js
│   ├── ipdms.js
│   ├── languageService.js
│   ├── NService.js
│   ├── NotificationService.js
│   ├── randomNumberGeneratorService.js
│   └── vms.js
├── resources
│   ├── angular-chart.css
│   ├── angular-material.css
│   ├── angular-ui-tree.min.css
│   ├── dist
│   │   ├── css
│   │   │   ├── bootstrap.css
│   │   │   ├── bootstrap.css.map
│   │   │   ├── bootstrap.min.css.map
│   │   │   ├── bootstrap-theme.css
│   │   │   ├── bootstrap-theme.css.map
│   │   │   ├── bootstrap-theme.min.css
│   │   │   └── bootstrap-theme.min.css.map
│   │   ├── fonts
│   │   │   ├── glyphicons-halflings-regular.eot
│   │   │   ├── glyphicons-halflings-regular.svg
│   │   │   ├── glyphicons-halflings-regular.ttf
│   │   │   ├── glyphicons-halflings-regular.woff
│   │   │   └── glyphicons-halflings-regular.woff2
│   │   └── js
│   │       └── bootstrap.js
│   ├── font-awesome
│   │   ├── bower.json
│   │   ├── css
│   │   │   ├── font-awesome.css
│   │   │   └── font-awesome.css.map
│   │   ├── fonts
│   │   │   ├── font-awesome.min.css
│   │   │   ├── FontAwesome.otf
│   │   │   ├── fontawesome-webfont.eot
│   │   │   ├── fontawesome-webfont.svg
│   │   │   ├── fontawesome-webfont.ttf
│   │   │   ├── fontawesome-webfont.woff
│   │   │   └── fontawesome-webfont.woff2
│   │   └── HELP-US-OUT.txt
│   ├── fonts
│   │   ├── XYZCorpSansBold.otf
│   │   ├── XYZCorpSansExtraLight.otf
│   │   ├── XYZCorpSansLight.otf
│   │   ├── XYZCorpSansRegular.otf
│   │   ├── XYZCorpSans.scss
│   │   ├── wingleader-icons.css
│   │   ├── wingleader_icons.eot
│   │   ├── wingleader_icons.svg
│   │   ├── wingleader_icons.ttf
│   │   └── wingleader_icons.woff
│   ├── images
│   │   ├── add-site-h
│   │   │   ├── branch-icon.svg
│   │   │   └── hub-icon.svg
│   │   ├── alarm-clock.png
│   │   ├── area.png
│   │   ├── clibboard.png
│   │   ├── clock-white.png
│   │   ├── close-btn.png
│   │   ├── deploy.png
│   │   ├── details-header
│   │   │   └── trash.svg
│   │   ├── down-arrow-gray.png
│   │   ├── down-triangle-filled.svg
│   │   ├── down-triangle.svg
│   │   ├── edit-details
│   │   │   └── scheduler.png
│   │   ├── edit-t
│   │   │   ├── application-prioritization.svg
│   │   │   ├── security_basic.svg
│   │   │   ├── security_enhanced.svg
│   │   │   └── security_high.svg
│   │   ├── grid-view-gray.png
│   │   ├── grid-view-white.png
│   │   ├── hamburger.png
│   │   ├── h-orange.png
│   │   ├── h-white.png
│   │   ├── icon-f.png
│   │   ├── icon-rating.svg
│   │   ├── icon-r.png
│   │   ├── icons
│   │   │   ├── alarm-clock.png
│   │   │   ├── area.png
│   │   │   ├── clibboard.png
│   │   │   ├── clock-white.png
│   │   │   ├── close-btn.png
│   │   │   ├── deploy.png
│   │   │   ├── down-arrow-gray.png
│   │   │   ├── grid-view-gray.png
│   │   │   ├── grid-view-white.png
│   │   │   ├── hamburger.png
│   │   │   ├── h-orange.png
│   │   │   ├── h-white.png
│   │   │   ├── info.png
│   │   │   ├── left-arrow-gray.png
│   │   │   ├── left-arrow-white.png
│   │   │   ├── line.png
│   │   │   ├── list-view-gray.png
│   │   │   ├── list-view-white.png
│   │   │   ├── loading-spinner.png
│   │   │   ├── search.png
│   │   │   ├── v-orange.png
│   │   │   ├── v-white.png
│   │   │   └── white-rock.png
│   │   ├── icon-server.png
│   │   ├── icon-ooo.png
│   │   ├── icon-ooo-portal-link.png
│   │   ├── icon-mcgruber-basic.svg
│   │   ├── icon-mcgruber-enhanced.svg
│   │   ├── icon-mcgruber-nextgen.svg
│   │   ├── icon-wf.png
│   │   ├── info.png
│   │   ├── languages
│   │   │   ├── de_DE.png
│   │   │   ├── en_GB.png
│   │   │   ├── en_US.png
│   │   │   ├── fr_FR.png
│   │   │   ├── hr_HR.png
│   │   │   ├── hu_HU.png
│   │   │   ├── it_IT.png
│   │   │   └── sk_SK.png
│   │   ├── left-arrow-gray.png
│   │   ├── left-arrow-white.png
│   │   ├── line.png
│   │   ├── list-view-gray.png
│   │   ├── list-view-white.png
│   │   ├── loading-spinner.png
│   │   ├── N-edit
│   │   │   ├── ivan-internet.svg
│   │   │   └── ivan-interweb.svg
│   │   ├── pagearrow_back.svg
│   │   ├── review
│   │   │   ├── rb-d.svg
│   │   │   ├── rb-routing.svg
│   │   │   ├── rb-services.svg
│   │   │   ├── rh-d.svg
│   │   │   ├── rh-routing.svg
│   │   │   ├── rh-services.svg
│   │   │   ├── rm-ivan-branches.svg
│   │   │   ├── rm-ivan-h.svg
│   │   │   ├── rm-ivan-quark.svg
│   │   │   ├── rm-ivan.svg
│   │   │   └── rm-ivan-w.svg
│   │   ├── sample-stats1.png
│   │   ├── sample-stats2.png
│   │   ├── search.png
│   │   ├── sd-review
│   │   │   └── arrow_right.svg
│   │   ├── users
│   │   │   ├── 0.png
│   │   │   ├── 1000.png
│   │   │   ├── 1001.png
│   │   │   ├── 1002.png
│   │   │   ├── 1003.png
│   │   │   ├── 1004.png
│   │   │   ├── 1005.png
│   │   │   ├── 1.png
│   │   │   ├── 2.png
│   │   │   └── 999.png
│   │   ├── abc-object-icons
│   │   │   ├── c-icon.svg
│   │   │   ├── ic-icon.svg
│   │   │   ├── N-f-icon.svg
│   │   │   ├── o-N-icon.svg
│   │   │   ├── search-code-icon.svg
│   │   │   ├── s-N-connection-icon.svg
│   │   │   ├── spi-icon.svg
│   │   │   └── vpwf-icon.svg
│   │   ├── v-orange.png
│   │   ├── v-white.png
│   │   └── white-rock.png
│   ├── ui-layout.css
│   └── abc.css
├── vendor.scss
└── views
    ├── components
    │   ├── activity-feed
    │   │   ├── activity-feed.html
    │   │   ├── activity-feed.js
    │   │   ├── _activity-feed.scss
    │   │   └── templates
    │   │       ├── pChange.html
    │   │       ├── snChange.html
    │   │       ├── sAdded.html
    │   │       ├── tChange.html
    │   │       └── tCreated.html
    │   ├── activity-panel
    │   │   ├── activity-panel.html
    │   │   ├── activity-panel.js
    │   │   ├── _activity-panel.scss
    │   │   └── templates
    │   │       ├── note.html
    │   │       ├── pChange.html
    │   │       ├── snChange.html
    │   │       ├── siteAdded.html
    │   │       ├── tChange.html
    │   │       └── tCreated.html
    │   ├── breadcrumb
    │   │   ├── breadcrumb.html
    │   │   └── breadcrumb.js
    │   ├── edit-t
    │   │   ├── edit-t.html
    │   │   ├── edit-t.js
    │   │   ├── _edit-t.scss
    │   │   └── service-config
    │   │       ├── _angular-slider.scss
    │   │       ├── options-bucket
    │   │       │   ├── options-bucket.html
    │   │       │   ├── options-bucket.js
    │   │       │   └── _options-bucket.scss
    │   │       ├── service-config.html
    │   │       ├── service-config.js
    │   │       └── _service-config.scss
    │   ├── map-view
    │   │   ├── map
    │   │   │   ├── leaflet-zoom-slider.js
    │   │   │   ├── _leaflet-zoom-slider.scss
    │   │   │   ├── marker-circle-template.html
    │   │   │   ├── _marker-circle-template.scss
    │   │   │   ├── marker-group-template.html
    │   │   │   └── _marker-group-template.scss
    │   │   ├── map-view.html
    │   │   ├── map-view.js
    │   │   └── _map-view.scss
    │   ├── summary-view
    │   │   ├── components
    │   │   │   ├── summary-view-header.html
    │   │   │   ├── summary-view-header.js
    │   │   │   ├── summary-view-section-content.html
    │   │   │   ├── summary-view-section-content.js
    │   │   │   ├── summary-view-section-header.html
    │   │   │   ├── summary-view-section-header.js
    │   │   │   ├── summary-view-section-image.html
    │   │   │   ├── summary-view-section-image.js
    │   │   │   ├── summary-view-section-template.html
    │   │   │   └── summary-view-section-template.js
    │   │   ├── summary-view-b.html
    │   │   ├── summary-view-h.html
    │   │   ├── summary-view-ivan.html
    │   │   ├── summary-view.js
    │   │   ├── summary-view-N.html
    │   │   └── _summary-view.scss
    │   ├── mcguffin-details
    │   │   ├── mcguffin-details.css
    │   │   ├── mcguffin-details.html
    │   │   ├── mcguffin-details.js
    │   │   └── _mcguffin-details.scss
    │   ├── mcguffin-panel
    │   │   ├── mcguffin-panel.html
    │   │   ├── mcguffin-panel.js
    │   │   └── _mcguffin-panel.scss
    │   └── mcgruber-selection
    │       ├── mcgruber-selection.html
    │       ├── mcgruber-selection.js
    │       └── _mcgruber-selection.scss
    ├── dashboard
    │   ├── dashboard.css
    │   ├── dashboard_demo.js
    │   ├── dashboard.html
    │   ├── dashboard.js
    │   └── dashboard.js.local
    ├── details
    │   ├── details.css
    │   ├── details_demo.js
    │   ├── details.html
    │   ├── details.js
    │   └── partials
    │       ├── some-modal.html
    │       ├── c.html
    │       └── gw.html
    ├── summarize
    │   ├── summarize.css
    │   ├── summarize_demo.js
    │   ├── summarize.html
    │   └── summarize.js
    ├── login
    │   ├── login.css
    │   ├── login_demo.js
    │   ├── login.html
    │   ├── login.js
    │   └── _login.scss
    ├── settings
    │   ├── passwordReqsTemplate.html
    │   ├── settings.css
    │   ├── settings_demo.js
    │   ├── settings.html
    │   ├── settings.js
    │   └── _settings.scss
    ├── t
    │   ├── someDataModal.html
    │   ├── scale-setup-mcguffinr-clean.json
    │   ├── scale-setup-mcguffinr.json
    │   ├── scale-setup-mcguffinr.json.bkup
    │   ├── scale-setup-mcguffinr.xml
    │   ├── single-mcguffinr-export.json
    │   ├── single-mcguffinr-export.template.json
    │   ├── single-mcguffinr-export.xml
    │   ├── t.css
    │   ├── t_demo.js
    │   ├── t.html
    │   ├── t.js
    │   ├── mcguffind-export.json
    │   ├── mcguffinr-collection-export.json
    │   ├── mcguffinr-collection-export.template.json
    │   └── mcguffinr-collection-nomcguffinr-export.json
    ├── abc
    │   ├── rcConfigureModal.html
    │   ├── rcDeployModal.html
    │   ├── rc.html
    │   ├── rc.js
    │   ├── subviews
    │   │   ├── rcCatalogs.html
    │   │   ├── rcInstances.html
    │   │   ├── rcInstances.js
    │   │   ├── rcNode.html
    │   │   ├── rcNode.js
    │   │   ├── mcguffinmDeployments.html
    │   │   ├── mcguffinmInstances.html
    │   │   ├── mcguffinmInstances.js
    │   │   ├── mcguffinmNode.html
    │   │   ├── mcguffinmNode.js
    │   │   ├── mcguffinmPeerInstance.html
    │   │   └── mcguffinmPeerInstance.js
    │   ├── abc.css
    │   ├── abc_home.html
    │   ├── abc.js
    │   ├── abc_logs.js
    │   ├── abc_next.html
    │   ├── abc_status.js
    │   ├── abc_viewingleaderogs.html
    │   ├── abc_wizard.html
    │   ├── mcguffinmDeployModal.html
    │   └── mcguffinmLogsModal.html
    └── mcguffinmonitoring
        ├── mcguffinmonitoring.css
        ├── mcguffinmonitoring_demo.js
        ├── mcguffinmonitoring.html
        └── mcguffinmonitoring.js
```

**Comment by rahulsom** [comment]
Do you still get the same exception?

**Comment by sanchezelton** [comment]
Yes, same error as well.

**Comment by rahulsom** [comment]
Sorry about that. I've gone another major version behind on stylelint. Try `0.1.3`.

**Comment by sanchezelton** [comment]
Does htmlcs have a dependency on stylelint? If not, it sounds unlikely that upgrading stylelint would fix this. Regardless, I gave it a go, but the issue remains the same. (I don't see that version tagged here in GitHub; so maybe it is not yet available?)

**Comment by rahulsom** [comment]
Take a look at this build: https://travis-ci.org/rahulsom/elton/jobs/197516674
Here's the repo: https://github.com/rahulsom/elton

Can you send a PR to that repo to break it?
